version: '3.8'
services:
  mathesar_db:
    image: postgres:15
    environment:
      POSTGRES_DB: mathesar
      POSTGRES_USER: mathesar
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/mathesar/:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  mathesar_service:
    image: mathesar/mathesar-prod:0.1.0
    environment:
      MODE: PRODUCTION
      DEBUG: "False"
      DJANGO_ALLOW_ASYNC_UNSAFE: "true"
      DJANGO_SETTINGS_MODULE: config.settings.production
      ALLOWED_HOSTS: "*"
      SECRET_KEY: secret
      DJANGO_DATABASE_KEY: default
      DJANGO_DATABASE_URL: "postgres://mathesar:password@mathesar_db:5432/mathesar"
      MATHESAR_DATABASES: "(mathesar_tables|postgresql://postgres:password@postgres:5432/postgres)"
      DJANGO_SUPERUSER_PASSWORD: password
    command: ./run.sh
    volumes:
      - ./volumes/static:/code/static
      - ./volumes/media:/code/media
    expose:
      - "8000"
    depends_on:
      mathesar_db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s

  caddy-reverse-proxy:
    image: mathesar/mathesar-caddy:0.1.0
    environment:
      DOMAIN_NAME: ":80"
    ports:
      - "8000:80"
    volumes:
      - ./volumes/media:/mathesar/media
      - ./volumes/static:/mathesar/static
      - ./volumes/caddy_data:/data
      - ./volumes/caddy_config:/config
    depends_on:
      mathesar_service:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

